openapi: 3.0.0
info:
  title: LMS Authentication API - Admin
  version: 1.0.0

paths:
  /api/admin-auth/login:
    post:
      tags:
        - Admin
      summary: Admin login
      description: Login as admin using credentials from environment variables
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: admin@example.com
                  description: Admin email (configured in .env)
                password:
                  type: string
                  format: password
                  example: admin123
                  description: Admin password (configured in .env)
      responses:
        '200':
          description: Admin login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Admin login successful
                  token:
                    type: string
                    description: JWT authentication token with admin privileges
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      name:
                        type: string
                        example: Admin
                      email:
                        type: string
                        example: admin@example.com
                      role:
                        type: string
                        example: ADMIN
        '401':
          description: Invalid admin credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid admin credentials
        '403':
          description: Admin credentials not configured
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Admin credentials not configured
